version: '3.8'

services:
  postgres:
    extends:
      file: ./scijourdex-backend/docker-compose.yml
      service: postgres

  backend:
    extends:
      file: ./scijourdex-backend/docker-compose.yml
      service: scijourdex-backend

  frontend:
    extends:
      file: ./scijourdex-frontend/docker-compose.yml
      service: scijourdex-frontend

    webscraper:
      extends:
        file: ./webscraper/docker-compose.yml
        service: webscraper

volumes:
  postgres-data: